### ISSUE TITLE
Search Query Tool - the ManagedProperties property does not contain values.

### ISSUE THREAD

**Issue by Shifu21** [wobba/SPO-Trigger-Reindex#2]
Today i'm installing the Search Query Tool v2.7 on Win10.
If i will connect to our customer and show "view all properties" i get a error message.

ManagedProperties property does not contain values. See https://github.com/wobba/SPO-Trigger-Reindex for more information on how to enable this feature.

So where i can enable this feature?! 

Best regards 
Mattias

![image](https://user-images.githubusercontent.com/20124484/31824306-e997d75e-b5ae-11e7-8619-3cab471468d9.png)

**Comment by wobba** [comment]
Go and read the info on that link :) a bit down the page

**Comment by Shifu21** [comment]
Thanks for your comment wobba but it doesn't work. I get always the same errormessage.
If i use Search Query Tool 2.6 i don't need the re-index workaround, but why?!

**Comment by wobba** [comment]
So you're saying 2.6 works, but 2.7 fails? If so I need to investigate.

**Comment by wobba** [comment]
@Shifu21 I just testet with v2.7 and I do get to see all properties. Note that this does not work if you use "SharePoint Online Management" as the sign-in method.

**Comment by wobba** [comment]
Cannot reproduce.
