### ISSUE TITLE
Access denied. You do not have permission to  perform this action or access this resource

### ISSUE THREAD

**Issue by jerryyasir** [wobba/SPO-Trigger-Reindex#3]
vti_searchversion property does not exist for Site or Web and then result in following error while setting it to 1 on Line 40 and 41 of both Site and tenant script. 

Exception calling "ExecuteQuery" with "0" argument(s): "Access denied. You do not have permission to 
perform this action or access this resource." 

I am using Global Admin account who has SCA on all site collections.

**Comment by wobba** [comment]
Regular SC, or a Group/comm site? Most likely the site collection is set as a NoScript site, which disallow web property bag modification. But, you can make it script enabled first, then run the ps1. My app works around this ;) not hard.

**Comment by wobba** [comment]
@jerryyasir any info?

**Comment by rubbat** [comment]
Hello wobba

How are you ? are you doing well ?

I enable script
https://support.office.com/en-us/article/allow-or-prevent-custom-script-1f2c515f-5d7e-448a-9fd7-835da935584f

but the issue persist

Thanks,
Best Regards

**Comment by wobba** [comment]
What kind of site collection is it? Shouldn't be an issue as long as script is enabled and not seen this before. If it's one site only go to seatch/offline settings on the root site and click "reindex this site".

**Comment by rubbat** [comment]
Hello wobba thanks for the fast repy i tried on admin center

![wk1](https://user-images.githubusercontent.com/36772149/36608871-0c0390cc-18c3-11e8-9372-471d210470c3.png)

and use this command

.\reindex-users.ps1 https://rubentenant-admin.sharepoint.com -username rubbat@rubentenant.onmicrosoft.com -password #####

**Comment by rubbat** [comment]
Thanks wobba I did reindex the root site, the next crawl is at 20:00, On Monday I will check this again

Best Regards

**Comment by wobba** [comment]
@rubbat so you are on-prem? I have never tested this script on-prem, and for on-prem you can always run a full crawl from the search service application - hence no need for this script.

**Comment by rubbat** [comment]
Hello wobba,


How are you ? are you doing well ?


No, I try this in online.


unfortunately still have the same issue 😞


Thanks,

Best Regards


________________________________
De: Mikael Svenson <notifications@github.com>
Enviado: segunda-feira, 26 de fevereiro de 2018 07:50
Para: wobba/SPO-Trigger-Reindex
Cc: rubbat; Mention
Assunto: Re: [wobba/SPO-Trigger-Reindex] Access denied. You do not have permission to perform this action or access this resource (#3)


@rubbat<https://github.com/rubbat> so you are on-prem? I have never tested this script on-prem, and for on-prem you can always run a full crawl from the search service application - hence no need for this script.

**Comment by rubbat** [comment]
![wk3](https://user-images.githubusercontent.com/36772149/36664926-0c4d52e4-1ade-11e8-926f-c4274b16e82e.png)
its well connected but after this, return the issue

**Comment by wobba** [comment]
@rubbat Then I'm curious where you see when the next crawl runs, as you stated it would run at 20:00. Where do you see this? And your error seems very clear, wrong username and password.

1. Are you a sharepoint admin?
2. Do you have MFA on your tenant? The script only support username/pw without MFA, and probably will fail if using custom adfs as well.

**Comment by rubbat** [comment]
multifactor is disabled and Im global admin

![wk2](https://user-images.githubusercontent.com/36772149/36667797-0dc56e96-1ae7-11e8-9a1f-6c2523331ba7.png)
![wk3](https://user-images.githubusercontent.com/36772149/36667798-0de2f420-1ae7-11e8-8ce5-cc4b4c2c39b8.png)

I think that in online the crawl jobs runs everyday in 4 hours intervals, 12:00, 16:00 and 20:00

**Comment by wobba** [comment]
Can you try the following:
```
$creds = Get-Credential
Connect-SPOService -Credential $creds -Url https://rubentenant-admin.sharepoint.com
Get-SPOSite -Identity https://rubentenant.sharepoint.com
```

**Comment by rubbat** [comment]
Hello wobba,

I also try with Connect-SPOService before  execute script

Best Regards

**Comment by rubbat** [comment]
Hello wobba i put credentials one by one and is working,

thanks for assistance 

best regards

**Comment by wobba** [comment]
@rubbat does that mean I can close the issue?

**Comment by rubbat** [comment]
yes of corse, sorry for didnt reply before


Best regards :)


________________________________
De: Mikael Svenson <notifications@github.com>
Enviado: terça-feira, 27 de fevereiro de 2018 13:29
Para: wobba/SPO-Trigger-Reindex
Cc: rubbat; Mention
Assunto: Re: [wobba/SPO-Trigger-Reindex] Access denied. You do not have permission to perform this action or access this resource (#3)


@rubbat<https://github.com/rubbat> does that mean I can close the issue?
