### ISSUE TITLE
Tenant Reindex 401 UnAuthorized 

### ISSUE THREAD

**Issue by CGouch2** [wobba/SPO-Trigger-Reindex#5]
Good day

We have a need to reindex our Entire SharePoint Online due to refiner/metadata changes and issues related to Search in some areas.  We have been directed to this page for your script.  I have installed the latest CSOM as indicated and ensured the path appears correct (update from \15 to \16 in this case as well).  My account running the script is a tenant GA and for every site that my account is not a member of the local Site Collection Admin (which is many as by default it is not of course), I am receiving the below error which I also presume is not actually setting any value as a result for reindex?  

-- Updated search version:  1
Exception calling "ExecuteQuery" with "0" argument(s): "The remote server returned an error: (401) Unauthorized."

In other rarer cases I may receive this in the output to host instead:

-- Updated search version:  1
Exception calling "ExecuteQuery" with "0" argument(s): "Access denied. You do not have permission to perform this
action or access this resource."

Which I also presume is producing a non-successful trigger?

Does my account being used to run the script actually need to be physically added to each site as a Site Collection Admin (minimum) in order for this script to process and work properly or have I done/configured something incorrectly?  We have years of SharePoint sites now so this will be a bit of a pickle to add and communicate a new "strange user" or group added to each site if that is the case :-)

As an FYI, the reindex-site targeted at a site that I'm the owner or added to the Site Collection Admin or any sites that I have noted passing by in the output that I'm the same has not produced those errors and incremented the -- Updated search version:   to 2 or 3 depending....  And a 'noob' question, what is the "search version" actually saying (and presume "1" is not a good value)

Thanks

**Comment by wobba** [comment]
Hi, the script should be execute by someone who is an SharePoint Online admin. Then you don't need to be a sc admin per site.

I'll probably rework the script to use PnP powershell, which might make it easier for most people to run.

**Comment by CGouch2** [comment]
Perfect, thanks for the response and update!   So, being or using a Global Admin account is not enough despite it's power?  That account should be added to the specific SharePoint Admin role as well, then?  Interesting, as I wrongly inferred being a GA account it would by default have that classification.  I can try this to see if it makes any difference.  

And the "update search version" number iteration if anything but '1' would be a sign it's tagged for recrawl, true assessment?  

Thanks

**Comment by wobba** [comment]
Global account should work, but modifying property bag values on modern/comm sites require you to enable scripting on the site first (Deny - Add and Customise Pages setting). That could be what you are experiencing. Which means that step should be added to the script. Enable scripting, update prop bag, disable scripting.

As for the increment it's a matter of changing the value from the last value. If it's different a recrawl will happen.

**Comment by wobba** [comment]
I have rewritten the scripts to use PnP PowerShell, which should help you out.

**Comment by CGouch2** [comment]
Thanks.  I'll check it out.  Appreciate your feedback/update


On Apr 17, 2019, at 4:48 AM, Mikael Svenson <notifications@github.com<mailto:notifications@github.com>> wrote:


I have rewritten the scripts to use PnP PowerShell, which should help you out.
