### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by AdamBilski** [wobba/SPO-Trigger-Reindex#6]
Hello,

Maybe a silly one but cannot resolve this.

When running the User Re-index it comes back with exception see attached.

![Untitled](https://user-images.githubusercontent.com/49685734/56215671-ec09d780-6057-11e9-8cea-221c88d39357.png)

Please help.

Regards,

Adam B.

**Comment by wobba** [comment]
If I rewrote this script to use PnP PowerShell, would that be better you think? :)

**Comment by AdamBilski** [comment]
Possibly yes. Although I would like to know what is causing this exception.
I have similar problem with the Mobile Phone from Azure AD to SPO sync where script runs but has no effect at all.

**Comment by AdamBilski** [comment]
Oh sorry this script was by Raymond Tishenko I thought it was by you as well.

**Comment by wobba** [comment]
The script will not take effect right away - you have to wait for items to be indexed. You can use `Get-PnPSearchCrawlLog` to check when an item was last indexed - or check the date if you get it via search.

I'll rewrite the script using PnP which makes auth easier especially with MFA. Expect it in a couple of hours or tomorrow :)

**Comment by AdamBilski** [comment]
Awesome, thanks. I am aware I used the script this morning and still no changes now. I will let it do its thing overnight and see if anything happens.

**Comment by AdamBilski** [comment]
I know this is not the script but I also know yo have worked along on writing the SPO Employee-Directory guide. I was wondering if you could explain to me how to get the JSON to work ? as the below wont be accepted.
"AboutMe", "AcountName","BaseOfficeLocation",
"Department","Interests","JobTitle","Memberships", "PastProjects",
"PreferredName", "Responsibilities", "Schools", "Skills", "WorkEmail",
"YomiDisplayName"

Thanks and sorry to be a pain.

**Comment by wobba** [comment]
Not sure what JSON you are referring to where. Re-index of profiles can take several hours as it runs on a schedule (which we don't know when it runs)

**Comment by AdamBilski** [comment]
Yes aware of that, will see what we get tomorrow morning. 

The JSON is from guide Hyperfish_Employee-Directory Guide:

Configure the Search Results web part, expand Display
Templates, and add the following fields to the Hit-highlighted
properties (JSON) section:
"AboutMe", "AcountName","BaseOfficeLocation",
"Department","Interests","JobTitle","Memberships", "PastProjects",
"PreferredName", "Responsibilities", "Schools", "Skills", "WorkEmail",
"YomiDisplayName"
The effect of adding the new hit-highlighted properties are
visualized in the figure below. 

But I am getting error "Cannot save all of the property settings for this Web Part. One or more errors have occurred. See below for details"

Thanks.

**Comment by wobba** [comment]
Haven't looked at those in a looooooong time :-) Reach out to Marc Anderson and he might be able to help.

**Comment by wobba** [comment]
I've updated the scripts to be based off PnP PowerShell now.
