### ISSUE TITLE
Where is reindex-tenant.ps1?

### ISSUE THREAD

**Issue by waaromikniet** [wobba/SPO-Trigger-Reindex#7]
I don't see it in the repo

**Comment by wobba** [comment]
I have removed it on request from search support :) I do understand why you want it, but triggering unneeded re-indexing puts a strain overall on the search farms.

**Comment by waaromikniet** [comment]
Thanks for the update. But it is still present on https://www.techmikael.com. Maybe should remove it there also.

**Comment by wobba** [comment]
@waaromikniet Updated.
